{% set version = '3.0-2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-car
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/car_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/car/car_{{ version }}.tar.gz
  sha256: df59a9ba8fed67eef5ddb8f92f2b41745df715d5695c71d562d7031513f37c50

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: alr4, boot, coxme, leaps, lmtest, Matrix, MatrixModels, rgl (>= 0.93.960), sandwich, SparseM, survival, survey
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-mass
    - r-abind
    - r-cardata >=3.0_0
    - r-lme4
    - r-maptools
    - r-mgcv
    - r-nlme
    - r-nnet
    - r-pbkrtest >=0.4_4
    - r-quantreg
    - r-rio

  run:
    - r-base
    - r-mass
    - r-abind
    - r-cardata >=3.0_0
    - r-lme4
    - r-maptools
    - r-mgcv
    - r-nlme
    - r-nnet
    - r-pbkrtest >=0.4_4
    - r-quantreg
    - r-rio

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('car')"           # [not win]
    - "\"%R%\" -e \"library('car')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://r-forge.r-project.org/projects/car/, https://CRAN.R-project.org/package=car,
    http://socserv.socsci.mcmaster.ca/jfox/Books/Companion/index.html
  license: GPL (>= 2)
  summary: ' Functions to Accompany J. Fox and S. Weisberg,  An R Companion to Applied Regression,
    Third Edition, Sage, in press.'

  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: car
# Version: 3.0-2
# Date: 2018-08-23
# Title: Companion to Applied Regression
# Authors@R: c(person("John", "Fox", role = c("aut", "cre"), email = "jfox@mcmaster.ca"), person("Sanford", "Weisberg", role = "aut", email = "sandy@umn.edu"), person("Brad", "Price", role = "aut", email = "brad.price@mail.wvu.edu"), person("Daniel", "Adler", role="ctb"), person("Douglas", "Bates", role = "ctb"), person("Gabriel", "Baud-Bovy", role = "ctb"), person("Ben", "Bolker", role="ctb"), person("Steve", "Ellison", role="ctb"), person("David", "Firth", role = "ctb"), person("Michael", "Friendly", role = "ctb"), person("Gregor", "Gorjanc", role = "ctb"), person("Spencer", "Graves", role = "ctb"), person("Richard", "Heiberger", role = "ctb"), person("Rafael", "Laboissiere", role = "ctb"), person("Martin", "Maechler", role="ctb"), person("Georges", "Monette", role = "ctb"), person("Duncan", "Murdoch", role="ctb"), person("Henric", "Nilsson", role = "ctb"), person("Derek", "Ogle", role = "ctb"), person("Brian", "Ripley", role = "ctb"), person("William", "Venables", role = "ctb"), person("Steve", "Walker", role="ctb"), person("David", "Winsemius", role="ctb"), person("Achim", "Zeileis", role = "ctb"), person("R-Core", role="ctb"))
# Depends: R (>= 3.2.0), carData (>= 3.0-0)
# Imports: abind, MASS, mgcv, nnet, pbkrtest (>= 0.4-4), quantreg, grDevices, utils, stats, graphics, maptools, rio, lme4, nlme
# Suggests: alr4, boot, coxme, leaps, lmtest, Matrix, MatrixModels, rgl (>= 0.93.960), sandwich, SparseM, survival, survey
# ByteCompile: yes
# LazyLoad: yes
# Description:  Functions to Accompany J. Fox and S. Weisberg,  An R Companion to Applied Regression, Third Edition, Sage, in press.
# License: GPL (>= 2)
# URL: https://r-forge.r-project.org/projects/car/, https://CRAN.R-project.org/package=car, http://socserv.socsci.mcmaster.ca/jfox/Books/Companion/index.html
# NeedsCompilation: no
# Packaged: 2018-08-23 18:27:23 UTC; jfox
# Author: John Fox [aut, cre], Sanford Weisberg [aut], Brad Price [aut], Daniel Adler [ctb], Douglas Bates [ctb], Gabriel Baud-Bovy [ctb], Ben Bolker [ctb], Steve Ellison [ctb], David Firth [ctb], Michael Friendly [ctb], Gregor Gorjanc [ctb], Spencer Graves [ctb], Richard Heiberger [ctb], Rafael Laboissiere [ctb], Martin Maechler [ctb], Georges Monette [ctb], Duncan Murdoch [ctb], Henric Nilsson [ctb], Derek Ogle [ctb], Brian Ripley [ctb], William Venables [ctb], Steve Walker [ctb], David Winsemius [ctb], Achim Zeileis [ctb], R-Core [ctb]
# Maintainer: John Fox <jfox@mcmaster.ca>
# Repository: CRAN
# Date/Publication: 2018-08-23 23:34:28 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
