travis:
  secure:
    BINSTAR_TOKEN: hnr6fZldopmmhie1nHGIx+KSq0nAY1Cy8DZSHG9YaOc3rEqA7anCiHJlszbUYZ79NZzGzldjCUWiWVf05/X6MzliXHU30EkmAKgyXAvs6bWDLa6NwCwEFQObMO35n83x1dJoG+gB+xNg7Sm6g9AimbEmOCyAZLT6oJBXtBoLCcXrUJm38lyGUecf6fq2KnNT/+7u9O7LenFj7UxeTZznV4jfYA57v4wT0DefSzCE5xKPQxEsVVeIcldamrffayG+MDHWq4LciNyIWFhhmx/KCne2CsF9rjCoViX55C+rJCGvn+kBrHPEF2v7NoX5rsknJNF8sYa6mTQp9PISqjEIshvd9KBgC6sh1G2iBtTPzEhuWmZz+NQN9hHZYdFovaS6hKtnui/U7bzNOo4FRpvdh0aKmSjeOdqesH2+Cv0kf5wSJ9ZKvEqXrlxLQ+Z2nMUdlhqk+D4ddWWuazdp4Y49zEbBeMgjmRAQeW+HH0B+2H/kh+FZ2z3Shz6ol6gEUh6q82ah0fcZkdYYriyc/+Axu1j9ByWvd69gJAG8GVfJLEQQTVmgtWEziH7grk7CZtDlMXJbHTLXceM3eijDI5+KAaPtTH5AUcGmVO0NAPCnSpW1gyhidwkEQ902ABxcDoWx04k4ksYovMDRoKqQFAp8xjQ2N4WwgDh+05ReUxugecc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
