travis:
  secure:
    BINSTAR_TOKEN: UBkIlM5nMZIh1pqaG99khMxCCzgrDrS8bvF7Pam5TQjJZqYq/aloH5cRdCFzpMx/a3SxDTctOjYpZlOzo/73WRn+CVzvFwBgpMQ7pz/GfE8jptttkxcYQCwBFJtsnmzpgDnJSfUyXN9wr7cDtaaxCtSZoaM3OkpNklvYfWUKYkvxQMiWNWQ0sxXfK2fVn5HZF1c8s4iay6opAZP7e/jxMq+Biel1K4bjGBU/KVAabN+XCDtZGfZclMj1fjEgGLnN15ZxIoxuwvIQrd/2wg+RrR2RBtPIrF7iTh5u55mTXu8JybmBZh6Wn0rYQbhBQpJi23iuEEeFKA31z7HdCM3R0Kddsxa7IpTgC5hl7fsGN9CV/UMtdi+aC13eOsVk0oZ1122TfoetezDRrVdju2y9zIQsn63Cqupl29BYDinmObX6ndrCxIdieL/vgqy3hiCE31JrIAhJg8jZLZEV3q7/ytrAvkXcdmWRdZhC6sM8iw/Ebugi92qul63jO40Z1+r/akkSNIbMPqxg1Vy1LXG2fcbU3FbLhyD1rBGm+QLKk/gnMwjWESfSTz6ktSwMwP4DJDZqPSPUwMDqWthhncbDo9RoUm2DA7jHm7PEfEEV2YfJVvIt24YIsDaINhv97tm7q1UT48EovtJ2HBIoNQxMHWplj3GyFSj/B0YR5rdxnw8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
