travis:
  secure:
    BINSTAR_TOKEN: ZBa2pGeau1WyOfgo7Lx6ZBxZXzUTPoquuutVyWZ2HB1A6w8PLxVXIu87GkFNQjjuRG7hrNJeAO9FmbIejNZrWzoNVXIIyERJTN/IntPyYHsOFxcR9efYsCt3Hf8TgGn4v3wXhohceMrCsqcbbnJ0mrZEX6t7tczx3gfpHdwH3byfNdy2nxfSsh256dFqsymN+161iFbKcE9zDrc+QHtqe5pRc2KjESVyydIWP/k5uVSfMeDwPINMO34gR/ol0sioBSaJ2xGGVwWN63cNSqJnp8RsNayTB/RZib1mSf6RLc8TVb9UoUFdQ6W8A8qDVQn2T8C2Rz0kRLAXc3fbQI0xXNKynyw2E7O3cM0Q8mGmlbc+rU0qMGQvI9lqRtoUK5Kosc9OtiqdW3YX38B6FGhxrSwJCbLbwtTxkmlCbptKWEMakggXbpEZ09xa9uaymwwsrsDeKYryhg61RPkxwplcKB+zyZDaaPnmeRZIgA2277LX70iubgpk0KhFCPWc8y2qPuUK5XYi8nzg0Lr7P9bqUV4ZpG3Ygc+Pdjg/BKTP7Hx7NexR7aEwDRIseUzK9HXkINM4OIh5/iVOq1ou2wE1OYN6zvB1lfkOERbYEyzQ6T55UfzHx1Ey2prdyRxlBVUniMESrnEGPuhAm3lCb5HnncqHI6/l3MNsCZFtMXyZAk8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
