travis:
  secure:
    BINSTAR_TOKEN: k3+vgn1ItkNTE422AQDSitr+w0vh32rSxF/hIldT8eG4SoMFuNxaZg9HDn8MxzAunv3Fav0l9tBZDQUQ2VYh9uAimn6M6/G23QOzi1eLYBA2NgfYwjDRXPLSzvzKl5oeYC3TkVfYz7q93rRcC08+DZNHVLmsXHhan7jPAurIKKj6do9cAJNWcEoek28LXoyO50M1+fabcARj0jAsb0xORP95ZZxONcJmmz0wI4wZexd5YOfCcE1cv4gnbUYQbFsl9dWLYcUTeWx/JN8p8q9as6LbDrvi6X6chOC0sxUGf/kIN267pAwRBoAefKjITIZ8Me51gVMwc1jfVlyNhTcVLWmaA7GB70HFImUrOgemCbStmC7B7LO971gu1paYPvpRBhli9LodMcUzrKNagGXEGe7C0A06jcCftR+22dedKpunzHtZpQduYbQ2hrDg9rtafN+Pc/rnnMdcRpbC3LBURpHl1ZbYfcZCsdE8kdwpBGR/VDwzZ/u5OmKUzlmBZ3DJF79kJf3tE6+bUc/P2isA04fxFxNH+XLHH+7sXEG5flMTaJ5fBbzLEXpzumkSSqo0issATMm0B148UeGPFBmIdGqcaDy5IoXWPpcdnRlzDr3GcVmtj6AEtdhTpkn31PnAgT8YO16cVF5LozR4n1b8YBKZ+D9Emzi++S26szMYvbo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
